---
- name: install packages
  become: true
  become_user: root
  apt:
    state: present
    name:         
      - htop
      - nmap
      - curl
      - wget
      - vim

- name: Install software from snap
  community.general.snap:
    name: 
      - atom
    classic: yes