---

- name: Add neofetch ppa
  ansible.builtin.apt_repository:
    repo: 'ppa:dawidd0811/neofetch'
    codename: focal

- name: install packages
  become: true
  become_user: root
  apt:
    state: present
    name:         
      - zsh
      - htop
      - nmap
      - curl
      - wget
      - vim
      - neofetch
      - chromium-browser

- name: Install software from snap
  community.general.snap:
    name: 
      - atom
    classic: yes
